# Generated by Django 5.2.8 on 2025-11-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='QRコード/バーコードにしたいテキスト', verbose_name='テキスト')),
                ('code_type', models.CharField(choices=[('qr_code', 'QRコード'), ('barcode', 'バーコード')], default='qr_code', help_text='QRコードまたはバーコードを選択', max_length=20, verbose_name='コードの種類')),
                ('qr_format', models.CharField(blank=True, choices=[('qr_code', 'QRコード'), ('micro_qr', 'マイクロQR')], default='qr_code', help_text='QRコードの場合の規格', max_length=20, verbose_name='QRコード規格')),
                ('barcode_format', models.CharField(blank=True, choices=[('code39', 'Code39'), ('code128', 'Code128'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('upce', 'UPC-E'), ('itf', 'ITF')], default='code128', help_text='バーコードの場合の規格', max_length=20, verbose_name='バーコード規格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'コードデータ',
                'verbose_name_plural': 'コードデータ',
                'ordering': ['-created_at'],
            },
        ),
    ]
